<?php

/**
 * @file
 * Adds ical functionality to Views.
 */

/**
 * Implements hook_autoload_info().
 */
function viewsicalexport_autoload_info() {
  return array(
    'ViewsicalexportPluginStyleIcalFeed' => 'views/viewsicalexport_plugin_style_ical_feed.inc',
    'ViewsicalexportPluginRowIcalFields' => 'views/viewsicalexport_plugin_row_ical_fields.inc',
  );
}

/**
 * Implements hook_hook_info().
 */
function viewsicalexport_hook_info() {
  $hooks = array(
    'viewsicalexport_export_html_alter',
    'viewsicalexport_export_raw_event_alter',
    'viewsicalexport_export_vevent_alter',
    'viewsicalexport_export_vcalendar_alter',
    'viewsicalexport_export_post_render_alter',
  );

  return array_fill_keys($hooks, array('group' => 'viewsicalexport'));
}

/**
 * Implements hook_views_api().
 */
function viewsicalexport_views_api() {
  return array(
    'api' => 3,
    'path' => backdrop_get_path('module', 'viewsicalexport') . '/views',
  );
}

/**
 * Custom helper function to convert dates.
 *
 * @param object $date
 *   BackdropDateTime object.
 * @param bool $date_only
 *   Whether cardinality should be full or date only.
 */
function viewsicalexport_ical_utc($date, $date_only = FALSE) {
  $stamp = $date->format('U');
  if ($date_only) {
    $utc = format_date($stamp, 'custom', 'Ymd', 'UTC');
  }
  else {
    $utc = format_date($stamp, 'custom', 'Ymd\THis\Z', 'UTC');
  }
  return $utc;
}

/**
 * Custom helper to sanitize text fields.
 */
function viewsicalexport_sanitize_text($text, $escape = TRUE) {
  $text = decode_entities($text);
  $text = strip_tags($text);
  if ($escape) {
    $text = addcslashes($text, ',;');
  }
  return trim($text);
}

/**
 * FIXME remove these...?
 */
/**
 * Exception class for generic exceptions thrown by this module.
 */
class DateIcalException extends Exception {}

/**
 * Exception used by iCal Fields for when a date field is blank.
 */
class BlankDateFieldException extends DateIcalException {}

/**
 * Exception thrown when the Feeds parser plugin fails.
 */
class DateIcalParseException extends DateIcalException {}
